version: "3"
services:
  spiderfoot:
    volumes:
      - spiderfoot-data:/var/lib/spiderfoot
    image: spiderfoot
    container_name: spiderfoot
    ports:
      - "5001:5001"
    restart: no

volumes:
  spiderfoot-data:
