services:
  timesketch-worker:
    volumes:
      - ${TIMESKETCH_CONFIG_PATH}:/etc/timesketch/
      - ${TIMESKETCH_UPLOAD_PATH}:/usr/share/timesketch/upload/
      - ${TIMESKETCH_LOGS_PATH}:/var/log/timesketch/
      - /opt/share/:/share/
      - /opt/maxmind-geoipupdate/geoip_data:/opt/maxmind
      - /opt/dfiq/dfiq:/etc/timesketch/dfiq
  nginx:
    volumes:
      - /opt/timesketch/ssl/:/ssl/
