---
- DFIR:
    - Timesketch:
        - icon: mdi-timelapse
          href: https://localhost
    - Yeti:
        - icon: mdi-foot-print
          href: https://localhost:8888
- OSINT:
    - Spiderfoot:
        - icon: mdi-spider
          href: http://localhost:5001
- Healper Apps:
    - Cyberchef:
        - icon: mdi-knife
          href: http://localhost:8080
